##################################################
# GET requests
##################################################

###
# get all phonebook entries
GET http://localhost:3001/api/persons

###
# get entry with ID 1
GET http://localhost:3001/api/persons/1

###
# try to get entry which doesn't exist
GET http://localhost:3001/api/persons/99

###
# get number of entries and current date and time
GET http://localhost:3001/info





##################################################
# DELETE requests
##################################################

###
# delete entry with ID 3
DELETE http://localhost:3001/api/persons/3





##################################################
# POST requests
##################################################

###
# create new entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Daniel Clarke",
  "number": "040 46777890"
}

###
# create new entry with no name or number
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###
# create new entry with no name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "040 46777890"
}

###
# create new entry with no number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Daniel Clarke"
}
